### ISSUE TITLE
How to use for Kaltura

### ISSUE THREAD

**Issue by robp2175** [kaltura/jQuery-File-Upload#4]
There is a lot of documentation for this plugin, but documentation regarding how to use it with Kaltura CE does not appear to exist. If someone could offer some guidance I would be greatly appreciative.

**Comment by mdale** [comment]
@itaykinnrot maybe we could make it a bit more clear how you replace the service / api url ?

**Comment by itaykinnrot** [comment]
hi you can use this example:http://kaltura.github.io/jQuery-File-Upload/ and edit the api URL here:
https://github.com/kaltura/jQuery-File-Upload/blob/gh-pages/index.html#L301

**Comment by robp2175** [comment]
Thank you, the first thing I did when I downloaded the script was change the api URLs. I also changed the url in line 302. However, it did not work for me, therefore, I thought there was a possibility I was missing something. I will check on it again.

**Comment by jessp01** [comment]
Hello @robp2175,

Any update on this?
